<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Shift Access - Thai Hung Corp</title>

    <meta name="description" content="Phần mềm chấm công nhà máy Thái Hưng">
    <meta name="author" content="Sweetsica!">

    <link href="{{asset('assets/css/bootstrap.min.css')}}" rel="stylesheet">
    <link href="{{asset('assets/css/style.css')}}" rel="stylesheet">

</head>
<body>

<div class="container-fluid">
    <h1>Shift Access - Thai Hung Corp</h1>
    <div class="row">
        <div class="col-md-12">
            <dl>
                <dt>
                    Description
                </dt>
                <dd>
                    Our software is used for the purpose of managing entry and exit within internal departments. It provides statistics on the number of entries, etc. The key functionalities include:
                </dd>
                <dd>
                    User data creation: User information, departments, facial data
                </dd>
                <dd>
                    Writing data to cards (Using NFC writer, a link)
                </dd>
                <dd>
                    Receiving data sent from NFC cards to the terminal machine, and pushing it via a link to our server
                </dd>
                <dd>
                    Processing and responding to the terminal machine to decide whether to unlock or not."
                </dd>

            </dl>
        </div>
    </div>
    <div class="row">
        <div class="col-md-4">
            <h2>
                List Detail - Create && Write
            </h2>
            <p>
                These data will be generated by us first. Then it will turn into links printed on the card. Has the form:<br>
                    <a href="#">{{env('APP_URL')}}/{userID?}/{token?}/{Department Id?}</a> <br>
                For example:<br>
                    <a href="#">{{env('APP_URL')}}/6/X2UHo/1</a> <br>
            </p>
            <table class="table">
                <thead>
                <tr>
                    <th>
                        #
                    </th>
                    <th>
                        Name
                    </th>
                    <th>
                        Token
                    </th>
                    <th>
                        Department Id
                    </th>
                </tr>
                </thead>
                <tbody>
                @foreach($member as $data)
                    <tr>
                        <td>
                            {{$data->id}}
                        </td>
                        <td>
                            {{$data->name}}
                        </td>
                        <td>
                            {{$data->token}}
                        </td>
                        <td>
                            {{$data->departmentId}}
                        </td>
                    </tr>
                @endforeach
                </tbody>
            </table>
        </div>
        <div class="col-md-4">
            <h2>
                Read and Send
            </h2>
            <p>
                We will have some private rooms, each room will be assigned a machine of yours with specific information (like Department name).
            </p>
            <ul>
                <li class="list-item">
                    Gateway <a href="#">{{env('APP_URL')}}/checkin/gateway/</a>
                </li>
                <li class="list-item">
                    Warehouse <a href="#">{{env('APP_URL')}}/checkin/warehouse/</a>
                </li>
                <li class="list-item">
                    Exhibition room <a href="#">{{env('APP_URL')}}/checkin/exhibitionroom/</a>
                </li>
                <li class="list-item">
                    Canteen <a href="#">{{env('APP_URL')}}/checkin/canteen/</a>
                </li>
            </ul>
            <p>
                With rules like:
            </p>
            <ol>
                <li class="list-item">
                    Everyone can only access the "Gateway"
                </li>
                <li class="list-item">
                    Only employees with odd ids can enter the "Warehouse"
                </li>
                <li class="list-item">
                    Only employees with even ids can access "Exhibition"
                </li>
                <li class="list-item">
                    No one can access "Canteen"
                </li>
            </ol>
            <p>
                When user active (by NFC card, faceID, finger print etc...)
            </p>
            <p class="list-item">
                Info will sent from machine: <a href="#">{{env('APP_URL')}}/checkin/{departmentName}/{userID?}/{token?}/active</a>
            </p>
            <ul>
                <li class="list-item">
                    User 3: <a href="#">{{env('APP_URL')}}/checkin/warehouse/3/b1cBa/active</a>
                </li>
                <li class="list-item">
                    User 4: <a href="#">{{env('APP_URL')}}/checkin/exhibition/4/Uiuvw/active</a>
                </li>
                <li class="list-item">
                    User 5: <a href="#">{{env('APP_URL')}}/checkin/canteen/5/C6eIp/active</a>
                </li>
                <li class="list-item">
                    User 6: <a href="#">{{env('APP_URL')}}/checkin/gateway/6/X2UHo/active</a>
                </li>
            </ul>

        </div>
        <div class="col-md-4">
            <h2>
                Feedback return from system
            </h2>
            <p>
                After our server receive info. It'll return: true - false as allow - not allow status to trigger locker
            </p>
            <table class="table">
                <thead>
                <tr>
                    <th>
                        #
                    </th>
                    <th>
                        UserName
                    </th>
                    <th>
                        Room
                    </th>
                    <th>
                        Status
                    </th>
                </tr>
                </thead>
                <tbody>
                <tr class="table-success">
                    <td>
                        3
                    </td>
                    <td>
                        Earl Stehr Sr.
                    </td>
                    <td>
                        Warehouse
                    </td>
                    <td>
                        Allow
                    </td>
                </tr>
                <tr class="table-success">
                    <td>
                        4
                    </td>
                    <td>
                        Alexandra Hagenes
                    </td>
                    <td>
                        Exhibition
                    </td>
                    <td>
                        Allow
                    </td>
                </tr>
                <tr class="table-danger">
                    <td>
                        5
                    </td>
                    <td>
                        Drake Blick
                    </td>
                    <td>
                        Canteen
                    </td>
                    <td>
                        Deny
                    </td>
                </tr>
                <tr class="table-success">
                    <td>
                        6
                    </td>
                    <td>
                        Mr. Deangelo Mueller
                    </td>
                    <td>
                        Gateway
                    </td>
                    <td>
                        Allow
                    </td>
                </tr>
                </tbody>
            </table>
        </div>
    </div>
    <div class="row">
        <div class="col-md-2">
        </div>
        <div class="col-md-8">
        </div>
        <div class="col-md-2">
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
        </div>
    </div>
</div>

<script src="{{asset('assets/js/jquery.min.js')}}"></script>
<script src="{{asset('assets/js/bootstrap.min.js')}}"></script>
<script src="{{asset('js/scripts.js')}}"></script>
</body>
</html>
